version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo This is ${ENV}
      - echo ${URL} # defined in BuildProject"
     #- NEXT_PUBLIC_DESIGN_URL=${NEXT_PUBLIC_DESIGN_URL}
     # - NEXT_PUBLIC_HEALTH_API=${NEXT_PUBLIC_HEALTH_API}
     # - NEXT_PUBLIC_API_BASE_URI=${NEXT_PUBLIC_API_BASE_URI}
     # - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - npm i
      - npm run build
      - npm run build:static --workspace=startrek
artifacts:
  base-directory: ./apps/startrek/out
  files:
    - '**/*'
