version: "3"

services:
  galaxy:
    container_name: galaxy
    build:
      context: .
      dockerfile: ./apps/galaxy/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  # api:
  #   container_name: startrek
  #   build:
  #     context: .
  #     dockerfile: ./apps/startrek/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
